<a href="https://colab.research.google.com/github/poorvautturkar25/Ann/blob/main/23uam135_exp_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Implement Different Loss Functions in a Neural Network
import numpy as np

# Sample Data (XOR)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [0]])

W = np.random.rand(2, 1)
b = np.random.rand(1)
lr = 0.1
epochs = 1000

def sigmoid(x):
    return 1 / (1 + np.exp(-x)) # Indented this line

def sigmoid_derivative(x):
    return x * (1 - x) # Indented this line

def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2) # Indented this line

def cross_entropy_loss(y_true, y_pred):
    eps = 1e-15
    y_pred = np.clip(y_pred, eps, 1 - eps)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred)) # Indented this line

loss_type = 'cross_entropy' # Change to 'mse' to use MSE

for epoch in range(epochs):
    z = np.dot(X, W) + b
    A = sigmoid(z)

    if loss_type == 'mse':
        loss = mse_loss(Y, A)
        d_loss = (Y - A) * sigmoid_derivative(A)
    elif loss_type == 'cross_entropy':
        loss = cross_entropy_loss(Y, A)
        d_loss = (A - Y)

    dW = np.dot(X.T, d_loss)
    db = np.sum(d_loss)

    W -= lr * dW
    b -= lr * db


output = sigmoid(np.dot(X, W) + b)
print("\nFinal Predictions:")
print(output.round())




Final Predictions:
[[0.]
 [0.]
 [0.]
 [1.]]


In [ ]:
#1. House Price Prediction (Regression – MSE Loss)
# Problem Statement:
# Predict the price of a house based on input features like number of rooms, area (sq ft), and
# location index.
#  Input: Numerical features (e.g., [3 rooms, 1500 sq ft, location index 0.7])
#  Output: Predicted price
#  Loss Function: Mean Squared Error (MSE)
#  Why MSE? Because output is continuous and exact value prediction matters.


import numpy as np

# Sample Data (House Price Prediction)
X = np.array([[3, 1500, 0.7],
              [2, 1000, 0.5],
              [4, 2000, 0.9],
              [5, 2500, 1.0]])

# Normalize input data
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X_normalized = (X - X_mean) / X_std

Y = np.array([[300000],
              [200000],
              [400000],
              [500000]])

# Initialize weights and bias randomly
np.random.seed(0)
W = np.random.randn(3, 1) * 0.01
b = np.zeros((1, 1))

# Learning rate and number of epochs
lr = 0.01
epochs = 1000

# Define the linear activation function
def linear_activation(x):
    return x

# Define the derivative of the linear activation function
def linear_derivative(x):
    return np.ones(x.shape)

# Define the Mean Squared Error (MSE) loss function
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Define a regression-friendly version of Cross-Entropy loss (not typical usage)
def cross_entropy_loss_regression(y_true, y_pred):
    eps = 1e-15
    y_pred = np.clip(y_pred, eps, np.inf)
    return np.mean((y_true - y_pred) ** 2 / (2 * y_pred ** 2) + np.log(y_pred))

# Training loop
for epoch in range(epochs):
    # Forward pass
    z = np.dot(X_normalized, W) + b
    A = linear_activation(z)

    # Calculate losses
    loss_mse = mse_loss(Y, A)
    loss_cross_entropy = cross_entropy_loss_regression(Y, A)

    # Backward pass (using MSE for gradient calculation)
    d_loss = (A - Y) * linear_derivative(A)

    # Calculate gradients
    dW = np.dot(X_normalized.T, d_loss)
    db = np.sum(d_loss, axis=0, keepdims=True)

    # Gradient clipping
    dW = np.clip(dW, -1, 1)
    db = np.clip(db, -1, 1)

    # Update weights and bias
    W -= lr * dW
    b -= lr * db

    # Print losses at certain intervals
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, MSE Loss: {loss_mse}, Cross-Entropy Loss (Regression): {loss_cross_entropy}")

# Make predictions
output = linear_activation(np.dot(X_normalized, W) + b)
print("\nFinal Predictions:")
print(output)

# Example prediction for a new input
new_input = np.array([[4, 2200, 0.8]])
new_input_normalized = (new_input - X_mean) / X_std
predicted_price = linear_activation(np.dot(new_input_normalized, W) + b)
print(f"\nPredicted price for new input: {predicted_price[0][0]}")


Epoch 0, MSE Loss: 134999992994.52713, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 100, MSE Loss: 134998624469.92982, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 200, MSE Loss: 134997255965.25075, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 300, MSE Loss: 134995887480.48988, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 400, MSE Loss: 134994519015.64723, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 500, MSE Loss: 134993150570.72281, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 600, MSE Loss: 134991782145.71663, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 700, MSE Loss: 134990413740.62866, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 800, MSE Loss: 134989045355.45892, Cross-Entropy Loss (Regression): 1.6249999999999998e+40
Epoch 900, MSE Loss: 134987676990.20743, Cross-Entropy Loss (Regression): 1.6249999999999998e+40

Final Predictions:
[[ -2.863440

In [ ]:
#2. Email Spam Detection (Binary Classification – Cross-Entropy Loss)
# Problem Statement:
# Classify an email as spam or not based on the frequency of certain keywords, sender address, and
# email length.
#  Input: Feature vector of email characteristics
#  Output: 0 (Not Spam) or 1 (Spam)
#  Loss Function: Binary Cross-Entropy Loss
#  Why Cross-Entropy? It measures the quality of classification probabilities.


import numpy as np

# Sample Data
X = np.array([[0.5, 0.2, 100],
              [0.1, 0.6, 500],
              [0.8, 0.4, 200],
              [0.3, 0.1, 300]])  # keyword frequency, sender score, email length

X = (X - np.mean(X, axis=0)) / np.std(X, axis=0)  # normalize X
Y = np.array([[1],
              [0],
              [1],
              [0]])  # 1 for spam, 0 for not spam

W = np.random.rand(3, 1) * 0.01  # initialize weights with smaller range
b = np.random.rand(1) * 0.01
lr = 0.01  # decrease learning rate
epochs = 1000

def sigmoid(x):
    x = np.clip(x, -100, 100)  # clip x to prevent overflow
    return 1 / (1 + np.exp(-x))

def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

def cross_entropy_loss(y_true, y_pred):
    eps = 1e-15
    y_pred = np.clip(y_pred, eps, 1 - eps)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

for epoch in range(epochs):
    z = np.dot(X, W) + b
    A = sigmoid(z)

    loss_mse = mse_loss(Y, A)
    loss_cross_entropy = cross_entropy_loss(Y, A)

    # Use cross-entropy loss for gradient calculation
    d_loss = (A - Y)

    dW = np.dot(X.T, d_loss)
    db = np.sum(d_loss)

    W -= lr * dW
    b -= lr * db

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, MSE Loss: {loss_mse:.4f}, Cross-Entropy Loss: {loss_cross_entropy:.4f}")

output = sigmoid(np.dot(X, W) + b)
print("\nFinal Predictions:")
print(output.round())

new_email = np.array([[0.6, 0.3, 250]])  # keyword frequency, sender score, email length
new_email = (new_email - np.mean(X, axis=0)) / np.std(X, axis=0)  # normalize new email
predicted_probability = sigmoid(np.dot(new_email, W) + b)
print(f"\nPredicted probability of being spam: {predicted_probability[0][0]:.4f}")
print(f"Predicted label: {np.round(predicted_probability)[0][0]}")

Epoch 0, MSE Loss: 0.2497, Cross-Entropy Loss: 0.6926
Epoch 100, MSE Loss: 0.0457, Cross-Entropy Loss: 0.2207
Epoch 200, MSE Loss: 0.0208, Cross-Entropy Loss: 0.1343
Epoch 300, MSE Loss: 0.0120, Cross-Entropy Loss: 0.0968
Epoch 400, MSE Loss: 0.0078, Cross-Entropy Loss: 0.0758
Epoch 500, MSE Loss: 0.0055, Cross-Entropy Loss: 0.0623
Epoch 600, MSE Loss: 0.0041, Cross-Entropy Loss: 0.0529
Epoch 700, MSE Loss: 0.0032, Cross-Entropy Loss: 0.0460
Epoch 800, MSE Loss: 0.0026, Cross-Entropy Loss: 0.0407
Epoch 900, MSE Loss: 0.0021, Cross-Entropy Loss: 0.0365

Final Predictions:
[[1.]
 [0.]
 [1.]
 [0.]]

Predicted probability of being spam: 0.0000
Predicted label: 0.0


In [ ]:
#3. Student Placement Prediction (Binary Classification – Cross-Entropy Loss)
# Problem Statement:
# Predict whether a student will be placed based on academic performance (10th %, 12th %,
# CGPA, and IQ score).
#  Input: Student feature vector
#  Output: 0 (Not Placed) or 1 (Placed)
#  Loss Function: Cross-Entropy Loss
#  Why Cross-Entropy? The problem is binary classification with probability output.


import numpy as np

# Sample Data
X = np.array([[85, 80, 8.5, 120],  # 10th %, 12th %, CGPA, IQ score
              [90, 85, 9.0, 110],
              [78, 75, 8.0, 100],
              [92, 90, 9.2, 125],
              [88, 85, 8.8, 115],
              [76, 70, 7.8, 90],
              [95, 92, 9.5, 130],
              [80, 75, 8.2, 105]])

Y = np.array([[1],  # Placed
              [1],
              [0],
              [1],
              [1],
              [0],
              [1],
              [0]])

# Initialize weights and bias
W = np.random.rand(4, 1)
b = np.random.rand(1)

# Learning rate and epochs
lr = 0.1
epochs = 1000

# Stable sigmoid function
def sigmoid(x):
    x = np.clip(x, -100, 100)  # Clip x to prevent overflow
    return 1 / (1 + np.exp(-x))

# Sigmoid derivative
def sigmoid_derivative(x):
    return x * (1 - x)

# Cross-entropy loss function
def cross_entropy_loss(y_true, y_pred):
    eps = 1e-15
    y_pred = np.clip(y_pred, eps, 1 - eps)
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Loss type
loss_type = 'cross_entropy'

for epoch in range(epochs):
    z = np.dot(X, W) + b
    A = sigmoid(z)

    if loss_type == 'cross_entropy':
        loss = cross_entropy_loss(Y, A)
        d_loss = (A - Y)

    dW = np.dot(X.T, d_loss)
    db = np.sum(d_loss)

    W -= lr * dW
    b -= lr * db

output = sigmoid(np.dot(X, W) + b)
print("\nFinal prediction:")
print(output.round())


Final prediction:
[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]]


In [ ]:
#4. Temperature Forecasting (Regression – MSE Loss)
# Problem Statement:
#Forecast next-day temperature using historical weather data.
#  Input: Time series features of temperature, humidity, wind speed, etc.
#  Output: Forecasted temperature
#  Loss Function: Mean Squared Error
#  Why MSE? Because prediction accuracy of real values is important.

import numpy as np

# Sample Data (Temperature Forecasting)
X = np.array([[20, 60, 5],
              [22, 50, 10],
              [18, 70, 3],
              [25, 40, 15]])

# Corresponding temperature values for the next day
Y = np.array([[22],
              [24],
              [19],
              [26]])

# Feature scaling
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X = (X - X_mean) / X_std

# Initialize weights and bias randomly
W = np.random.rand(3, 1)
b = np.random.rand(1)

# Learning rate and number of epochs
lr = 0.0001  # Significantly reduced learning rate
epochs = 1000

# Define the linear activation function
def linear_activation(x):
    return x

# Define the derivative of the linear activation function
def linear_derivative(x):
    return np.ones(x.shape)

# Define the Mean Squared Error (MSE) loss function
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Define a regression-friendly version of Cross-Entropy loss (not typical usage)
def cross_entropy_loss_regression(y_true, y_pred):
    eps = 1e-15
    y_pred = np.clip(y_pred, eps, np.inf)
    return np.mean((y_true - y_pred) ** 2 / (2 * y_pred ** 2) + np.log(y_pred))

# Training loop
for epoch in range(epochs):
    # Forward pass
    z = np.dot(X, W) + b
    A = linear_activation(z)

    # Calculate losses
    loss_mse = mse_loss(Y, A)
    loss_cross_entropy = cross_entropy_loss_regression(Y, np.abs(A))  # Use absolute values for cross-entropy

    # Backward pass (using MSE for gradient calculation)
    d_loss = (A - Y) * linear_derivative(A)

    # Calculate gradients
    dW = np.dot(X.T, d_loss)
    db = np.sum(d_loss)

    # Update weights and bias
    W -= lr * dW
    b -= lr * db

    # Print losses at certain intervals
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, MSE Loss: {loss_mse}, Cross-Entropy Loss (Regression): {loss_cross_entropy}")

# Make predictions
output = linear_activation(np.dot(X, W) + b)
print("\nFinal Predictions:")
print(output)

# Example prediction for a new input
new_input = np.array([[23, 55, 8]])  # temperature, humidity, wind speed
new_input = (new_input - X_mean) / X_std  # Scale new input
predicted_temperature = linear_activation(np.dot(new_input, W) + b)
print(f"\nPredicted temperature for new input: {predicted_temperature[0][0]}")

Epoch 0, MSE Loss: 514.5789081174728, Cross-Entropy Loss (Regression): 572.097206788924
Epoch 100, MSE Loss: 474.7610501840255, Cross-Entropy Loss (Regression): 1814.749090918225
Epoch 200, MSE Loss: 438.06333793353343, Cross-Entropy Loss (Regression): 1019.5373962832267
Epoch 300, MSE Loss: 404.23347564910665, Cross-Entropy Loss (Regression): 79.1310595705188
Epoch 400, MSE Loss: 373.04119213016924, Cross-Entropy Loss (Regression): 30.107834703310946
Epoch 500, MSE Loss: 344.2759903047946, Cross-Entropy Loss (Regression): 16.463024089339292
Epoch 600, MSE Loss: 317.7451880450763, Cross-Entropy Loss (Regression): 10.72764823071813
Epoch 700, MSE Loss: 293.27220271808915, Cross-Entropy Loss (Regression): 7.797699736505824
Epoch 800, MSE Loss: 270.6950409765037, Cross-Entropy Loss (Regression): 6.119290373155934
Epoch 900, MSE Loss: 249.8649624452274, Cross-Entropy Loss (Regression): 5.0828278910779945

Final Predictions:
[[ 6.32114849]
 [ 8.27004131]
 [ 5.07490711]
 [10.65676144]]

Pred